@baseUrl=http://localhost:3000
@postId = 697e6814458c57a687f99d2c
@commentId = 

########## POSTS Requests ##########

### Add a new post
POST {{baseUrl}}/posts
Content-Type: application/json

{
      "title": "Bad Romance",
      "content": "Caught in a bad romance",
      "sender": "LadyGaga"
}

### Get All Posts 
GET {{baseUrl}}/posts

### Get All Posts by Sender
GET {{baseUrl}}/posts?sender=LadyGaga

### Get a Post by ID
GET {{baseUrl}}/posts/{{postId}}

### Update a Post
PUT {{baseUrl}}/posts/{{postId}}
Content-Type: application/json

{
  "title": "Diamonds",
  "owner": "Rihanna",
  "content": "Shine bright like a diamond"
}

########## COMMENTS Requests ##########

### Add a new comment
POST {{baseUrl}}/comments
Content-Type: application/json

{
  "post": "{{postId}}",
  "content": "This is a comment",
  "sender": "Beyonce"
}